import { createSlice } from '@reduxjs/toolkit';

const wledEffectsSlice = createSlice({
  name: 'effectLabels',
  initialState: [
    'Solid',
    'Blink',
    'Breathe',
    'Wipe',
    'Wipe Random',
    'Random Colors',
    'Sweep',
    'Dynamic',
    'Colorloop',
    'Rainbow',
    'Scan',
    'Scan Dual',
    'Fade',
    'Theater',
    'Theater Rainbow',
    'Running',
    'Saw',
    'Twinkle',
    'Dissolve',
    'Dissolve Rnd',
    'Sparkle',
    'Sparkle Dark',
    'Sparkle+',
    'Strobe',
    'Strobe Rainbow',
    'Strobe Mega',
    'Blink Rainbow',
    'Android',
    'Chase',
    'Chase Random',
    'Chase Rainbow',
    'Chase Flash',
    'Chase Flash Rnd',
    'Rainbow Runner',
    'Colorful',
    'Traffic Light',
    'Sweep Random',
    'Running 2',
    'Red & Blue',
    'Stream',
    'Scanner',
    'Lighthouse',
    'Fireworks',
    'Rain',
    'Merry Christmas',
    'Fire Flicker',
    'Gradient',
    'Loading',
    'Police',
    'Police All',
    'Two Dots',
    'Two Areas',
    'Circus',
    'Halloween',
    'Tri Chase',
    'Tri Wipe',
    'Tri Fade',
    'Lightning',
    'ICU',
    'Multi Comet',
    'Scanner Dual',
    'Stream 2',
    'Oscillate',
    'Pride 2015',
    'Juggle',
    'Palette',
    'Fire 2012',
    'Colorwaves',
    'Bpm',
    'Fill Noise',
    'Noise 1',
    'Noise 2',
    'Noise 3',
    'Noise 4',
    'Colortwinkles',
    'Lake',
    'Meteor',
    'Meteor Smooth',
    'Railway',
    'Ripple',
    'Twinklefox',
    'Twinklecat',
    'Halloween Eyes',
    'Solid Pattern',
    'Solid Pattern Tri',
    'Spots',
    'Spots Fade',
    'Glitter',
    'Candle',
    'Fireworks Starburst',
    'Fireworks 1D',
    'Bouncing Balls',
    'Sinelon',
    'Sinelon Dual',
    'Sinelon Rainbow',
    'Popcorn',
    'Drip',
    'Plasma',
    'Percent',
    'Ripple Rainbow',
    'Heartbeat',
  ],
  reducers: {
    update(state, action) {
      console.log('input: ', action.payload);
      console.log('state: ', state);
      state.length = 0;
      state.push(...action.payload);
    },
  },
});

export const { actions } = wledEffectsSlice;
export default wledEffectsSlice;
